name: 'dbt_queimadas'
version: '1.0.0'
config-version: 2

profile: 'queimadas_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

on-run-start:
  - "create schema if not exists s3_bronze;"

vars:
  bucket_name: "meu-data-lake-queimadas-2026"

models:
  dbt_queimadas:
    # Dados brutos
    bronze:
        +materialized: view

    # Dados serão tratados
    silver:
        +materialized: table

    # Base para criar os modelos dimensionais (Fatos e Dimensões)
    gold:
      +materialized: table