version: 2

models:
  - name: stg_nasa
    description: "Tabela Silver com dados limpos e tipados da NASA FIRMS"
    columns:
      - name: latitude
        tests:
          - not_null
      - name: longitude
        tests:
          - not_null

  - name: fato_final
    description: "Tabela Fato Gold de focos de calor processados"
    columns:
      - name: id_foco
        tests:
          - unique
          - not_null
      - name: intensidade_fogo_mw
        tests:
          - not_null