version: 2

models:
  - name: stg_nasa_queimadas
    description: "Tabela Silver com dados limpos e tipados da NASA FIRMS"
    columns:
      - name: latitude
        tests:
          - not_null
      - name: longitude
        tests:
          - not_null

  - name: fct_focos_queimadas
    description: "Tabela Fato Gold de focos de calor processados"
    columns:
      - name: sk_foco
        tests:
          - unique
          - not_null
      - name: severidade_fogo
        tests:
          - accepted_values:
              values: ['Baixa', 'Média', 'Alta', 'Indeterminada']