name: Data Pipeline E2E Dev Deployment

on:
  push:
    branches: [ "developer" ]
  pull_request:
    branches: [ "developer" ]

jobs:
  integration_test:
    runs-on: ubuntu-latest

    steps:
      # 1. Faz o download do código do repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-duckdb pandas requests boto3

      - name: Run API Ingestion Script (Upload to S3 Bronze)
        env:
          NASA_MAP_KEY: ${{ secrets.NASA_MAP_KEY }}
          AWS_DATA_LAKE_BUCKET: "meu-data-lake-queimadas-2026"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          python src/csmd_api.py

      - name: Setup dbt Profile with S3 support
        run: |
          mkdir -p ~/.dbt
          echo "
          queimadas_profile:
            target: dev
            outputs:
              dev:
                type: duckdb
                path: 'queimadas.duckdb'
                extensions:
                  - httpfs
                  - aws
                settings:
                  s3_region: 'us-east-1'
                  s3_access_key_id: \"${{ secrets.AWS_ACCESS_KEY_ID }}\"
                  s3_secret_access_key: \"${{ secrets.AWS_SECRET_ACCESS_KEY }}\"
          " > ~/.dbt/profiles.yml

      - name: Execute dbt Models
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          cd dbt_queimadas
          dbt run

      - name: Run dbt Quality Tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          cd dbt_queimadas
          dbt test