name: Data Pipeline E2E Dev Deployment

on:
  push:
    branches: [ "developer" ]
  pull_request:
    branches: [ "developer" ]

jobs:
  integration_test:
    runs-on: ubuntu-latest

    steps:
      # Faz o download do código do repositório para a máquina virtual do GitHub
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-duckdb pandas requests boto3

      - name: Run API Ingestion Script (Upload to S3 Bronze)
        env:
          NASA_MAP_KEY: ${{ secrets.NASA_MAP_KEY }}
        run: |
          python src/csmd_api.py

      # 6. Configura o perfil do dbt para usar o DuckDB habilitando o plugin do S3
      - name: Setup dbt Profile with S3 support
        run: |
          mkdir -p ~/.dbt
          echo "
          queimadas_profile:
            target: dev
            outputs:
              dev:
                type: duckdb
                path: 'queimadas.duckdb'
                plugins:
                  - s3
          " > ~/.dbt/profiles.yml

      - name: Execute dbt Models
        run: |
          cd dbt_queimadas
          dbt run

      - name: Run dbt Quality Tests
        run: |
          cd dbt_queimadas
          dbt test